<a href="https://colab.research.google.com/github/apoorva211/Ybi_projects_here/blob/main/DiabetesPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

**Importing Dataset named as diab**

> Add blockquote



In [ ]:
diab=pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Diabetes.csv")

# **Get the first five rows of data frame**

In [ ]:
diab.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

**Get information of dataframe**





In [ ]:
diab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


**Get the summary statistics**

In [ ]:
diab.describe()

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

**Get column names**

In [ ]:
diab.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

**Get shape of dataframe**

In [ ]:
diab.shape

(768, 9)

**Get unique values(class or label) in y variable**

In [ ]:
diab['diabetes'].value_counts()

diabetes
0    500
1    268
Name: count, dtype: int64

In [ ]:
diab.groupby('diabetes').mean()

pregnancies     glucose  diastolic    triceps     insulin  \
diabetes                                                              
0            3.298000  109.980000  68.184000  19.664000   68.792000   
1            4.865672  141.257463  70.824627  22.164179  100.335821   

                bmi       dpf        age  
diabetes                                  
0         30.304200  0.429734  31.190000  
1         35.142537  0.550500  37.067164

**Define y(dependent,label or target) variable and x(independent, attribute or feature) variable**

In [ ]:
y=diab['diabetes']
x=diab[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes']]

In [ ]:
y.shape

(768,)

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: diabetes, Length: 768, dtype: int64

In [ ]:
x.shape

(768, 9)

In [ ]:
x

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0              6      148         72       35        0  33.6  0.627   50   
1              1       85         66       29        0  26.6  0.351   31   
2              8      183         64        0        0  23.3  0.672   32   
3              1       89         66       23       94  28.1  0.167   21   
4              0      137         40       35      168  43.1  2.288   33   
..           ...      ...        ...      ...      ...   ...    ...  ...   
763           10      101         76       48      180  32.9  0.171   63   
764            2      122         70       27        0  36.8  0.340   27   
765            5      121         72       23      112  26.2  0.245   30   
766            1      126         60        0        0  30.1  0.349   47   
767            1       93         70       31        0  30.4  0.315   23   

     diabetes  
0           1  
1           0  
2           1  
3           0  
4           1  
..        ...  
763         0  
764         0  
765         0  
766         1  
767         0  

[768 rows x 9 columns]

**Get X variable Standerdised**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
nm=MinMaxScaler()

In [ ]:
x=nm.fit_transform(x)

In [ ]:
x

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.23441503, 0.48333333,
        1.        ],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.11656704, 0.16666667,
        0.        ],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.25362938, 0.18333333,
        1.        ],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.07130658, 0.15      ,
        0.        ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.11571307, 0.43333333,
        1.        ],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.10119556, 0.03333333,
        0.        ]])

**Get Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=2529)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((537, 9), (231, 9), (537,), (231,))

**Get Model train/select model**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()

**Train model**

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

**Get Model Prediction**

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0])

**Get probablity of each prdicted class**

In [ ]:
model.predict_proba(x_test)

array([[0.04711595, 0.95288405],
       [0.98223   , 0.01777   ],
       [0.97719549, 0.02280451],
       [0.98342891, 0.01657109],
       [0.98303556, 0.01696444],
       [0.04605887, 0.95394113],
       [0.03464645, 0.96535355],
       [0.98214026, 0.01785974],
       [0.97631919, 0.02368081],
       [0.97896815, 0.02103185],
       [0.98258444, 0.01741556],
       [0.03558087, 0.96441913],
       [0.98100827, 0.01899173],
       [0.98354567, 0.01645433],
       [0.976846  , 0.023154  ],
       [0.9828514 , 0.0171486 ],
       [0.97425346, 0.02574654],
       [0.05280872, 0.94719128],
       [0.03949286, 0.96050714],
       [0.97742175, 0.02257825],
       [0.97683845, 0.02316155],
       [0.98464466, 0.01535534],
       [0.98428341, 0.01571659],
       [0.97468151, 0.02531849],
       [0.97928211, 0.02071789],
       [0.03594001, 0.96405999],
       [0.98371934, 0.01628066],
       [0.97749019, 0.02250981],
       [0.97790897, 0.02209103],
       [0.02778997, 0.97221003],
       [0.

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[150   0]
 [  0  81]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00        81

    accuracy                           1.00       231
   macro avg       1.00      1.00      1.00       231
weighted avg       1.00      1.00      1.00       231



**Get Future Preidction**




*   Steps:
*   extract a random row using sample function
*   seperate x and y
*   standardise x
*   predict  



In [ ]:
x_new=diab.sample(1)

In [ ]:
x_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
472            0      119         66       27        0  38.8  0.259   22   

     diabetes  
472         0

In [ ]:
x_new.shape

(1, 9)

In [ ]:
x_new=nm.fit_transform(x_new)

In [ ]:
y_pred_new=model.predict(x_new)

In [ ]:
y_pred_new

array([0])

In [ ]:
model.predict_proba(x_new)

array([[0.99172195, 0.00827805]])

**Predicted and actual class is zero that is non diabetic**







Sample 2
```
# This is formatted as code
```



In [ ]:
x_new2=diab.sample(2)


In [ ]:
x_new2

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
210            2       81         60       22        0  27.7  0.290   25   
745           12      100         84       33      105  30.0  0.488   46   

     diabetes  
210         0  
745         0

In [ ]:
x_new2.shape

(2, 9)

In [ ]:
model.predict(x_new2)

array([0, 0])

In [ ]:
x_new2=nm.fit_transform(x_new2)

In [ ]:
model.predict_proba(x_new2)

array([[0.99172195, 0.00827805],
       [0.90606453, 0.09393547]])

In [ ]:
model.predict_proba(x_new2)

array([[0.99172195, 0.00827805],
       [0.90606453, 0.09393547]])

In [ ]:
model.predict_proba(x_new2)

array([[0.99172195, 0.00827805],
       [0.90606453, 0.09393547]])